# Create arrays with all the data types available in numpy

In [1]:
#Datatype integer

import numpy as np
a = np.array([21, 42, 43, 90], dtype = 'int_')
print(a)
print(a.dtype)

[21 42 43 90]
int32


In [2]:
#Datatype bool

a = np.array([False, False, True, True], dtype = 'bool_')
print(a)
print(a.dtype)

[False False  True  True]
bool


In [3]:
#Datatype float

a = np.array([23.6, 2.94, 332.3, 34.6], dtype = 'float_')
print(a)
print(a.dtype)

[ 23.6    2.94 332.3   34.6 ]
float64


In [4]:
#Datatype complex

a = np.array([16+3j, 26+4j, 64+8.7j, 18+3.4j], dtype = 'complex_')
print(a)
print(a.dtype)

[1.+3.j  2.+4.j  6.+8.7j 8.+3.4j]
complex128


In [5]:
#Datatype string

a = np.array(['a', 'b', 'c', 'd'], dtype = 'S')
print(a)
print(a.dtype)

[b'a' b'b' b'c' b'd']
|S1


In [9]:
#Datatype object

a = np.array([[451, 32], [36, 42], [4.65, 7.42], ['candice', 'Ferb']], dtype = 'O')
print(a)
print(a.dtype)

[[451 32]
 [36 42]
 [4.65 7.42]
 ['candice' 'Ferb']]
object


In [10]:
#Datatype unicode

a = np.array([1, 2, 3, 4], dtype = 'U')
print(a)
print(a.dtype)

['1' '2' '3' '4']
<U1


In [11]:
#Datatype unsigned integer

a = np.array([1, 2, 3, 4], dtype = 'uint8')
print(a)
print(a.dtype)

[1 2 3 4]
uint8
